# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3555d60d69b5e21544e24844230acde8"
name = "discount-allocator-app"
handle = "discount-allocator-app-3"
application_url = "https://murder-documentary-amended-onto.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "usama-discount-allocator-poc.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_discounts_allocator_functions,write_products"

[auth]
redirect_urls = [
  "https://murder-documentary-amended-onto.trycloudflare.com/auth/callback",
  "https://murder-documentary-amended-onto.trycloudflare.com/auth/shopify/callback",
  "https://murder-documentary-amended-onto.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
